### ISSUE TITLE
通过缓存 sell_conflict_checker 函数结果得到容易获得的性能提升

### ISSUE THREAD

**Issue by HeroTch** [Konano/snowsant-calculator#7]
使用 functools.cache 或 functools.lrucache 来缓存结果 [sell_conflict_checker](https://github.com/Konano/snowsant-calculator/blob/8a3a4e02207e054c86343986e75a2cc3943f4e18/run.py#L261)，使用 @cache decorator
profile 时发现第一次计算的耗时大部分在千万级调用该函数，阅读代码发现该函数应该是纯函数适合缓存（可能，需要确认）

AMD Ryzen 3700x 下可以将 耗时 ~50s降低到 ~15s

> [\*] 今日经营的商品是哪个阶段的商品？(1-4) 2
[\*] 今日的饮品爱好者有多少？270
[\*] 今日的餐点爱好者有多少？810
[\*] 今日的纪念品爱好者有多少？80
[\*] 雪雉商店的纪念品库存有多少（不知道的话填 0 即可）？6
[\*] 时光商店的纪念品库存有多少（不知道的话填 0 即可）？0
[\*] 是否允许用更少的当日收入换取更多的未来期望收入？需要更久的计算时间。0 为否，1 为是 (0/1) 1
[!] 请注意，后续的期望收益包括纪念品库存未来可能的收益。
[\*] 请输入可打探的次数：5

该示例输入，内存水平只有 ~100MiB 增长不大，也可以考虑使用 lrucache

**Comment by Konano** [comment]
原来还有这种优化操作，学习！

**Comment by Konano** [comment]
fixed by #8
